run:
  timeout: 5m

linters:
  enable:
    - goimports
    - gocognit
    - revive

linters-settings:
  gocognit:
    min-complexity: 10
  
  revive:
    rules:
      - name: var-naming
      - name: function-naming
      - name: exported
      - name: package-comments

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 